theme: jekyll-theme-minimal
title: Katta Rishibabu's Portfolio
description:
  Welcome to my personal portfolio showcasing my projects, skills, and certifications.
  Specializing in Electronics and Communication Engineering with a focus on VLSI.
