theme: jekyll-theme-minimal
logo: "/My Passport pic.jpg"
description:
  Welcome to my personal portfolio showcasing my projects, skills, and certifications.
  Specializing in Electronics and Communication Engineering with a focus on VLSI.
